[package]
name = "gt_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rsa = "0.9.6"

# block-modes = "0.8"
aes = "^0.8"
cbc = "0.1.2"

hex = "0.4.3"
hex-literal = "0.4.1"

md-5 = "0.10.6"
